### ISSUE TITLE
Library not working with scout version ^4.0 on Laravel 5.6.*

### ISSUE THREAD

**Issue by laalex** [grey-dev-0/laravel-scout-solr#1]
The library is not working with scount ^4.0 on the latest version of Laravel. This is due to the fact that in the library's composer.json file the scout version required is ~3.0|~2.0. 

Can you have an update for this please?

**Comment by grey-dev-0** [comment]
I've updated composer.json file to support scout 4.0 as well in da346b3c67d6a90643b6d2dda8e5635322c0d863
so, please try requiring again.. It's not tested if it works though.
If you find anything when using the package please do let me know.
